version: '3'
services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8083:8083"
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
